[env]
RUST_TEST_THREADS = { value = "1" }

[build]
target = "x86_64-unknown-linux-gnu"

#[target.x86_64-unknown-linux-gnu]
#linker = "rust-lld"
#rustflags = ["-C", "link-arg=--target=x86_64-linux-gnu"]